name: "Suggestion"
description: "Suggest an idea for the website"
labels: "enhancement"
title: "[SUGGEST] <title>"

body:
  - type: dropdown
    attributes:
      label: "The suggestion is related to? (You can choose more than one)"
      multiple: true
      options:
        - Minecraft Bedrock Edition
        - Minecraft Java Edition
        - Miscellaneous
        - Others
      required: true
  
 - type: textarea
    attributes:
      label: "Details"
      placeholder: "Write your suggestion details here""
    validations:
      required: true
